apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alloyrag.fullname" . }}-env
  labels:
    {{- include "alloyrag.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |-
    {{- include "alloyrag.envContent" . | nindent 4 }}
